SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
	public class CartIndexViewModel
	{
		public Cart Cart { get; set; }
		public string ReturnUrl { get; set; }
	}
}

SportsStore.WebUI/Models/ErrorViewModel.cs
namespace SportsStore.WebUI.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

SportsStore.WebUI/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SportsStore.WebUI.Models
{
	public class LoginViewModel
	{
		[Required]
		public string UserName { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
	}
}

SportsStore.WebUI/Models/PagingInfo.cs
namespace SportsStore.WebUI.Models
{
	public class PagingInfo
	{
		public int TotalItems { get; set; }
		public int ItemsPerPage { get; set; }
		public int CurrentPage { get; set; }
		public int TotalPages
		{
			get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
		}
	}
}

SportsStore.WebUI/Models/ProductsListViewModel.cs
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
	public class ProductsListViewModel
	{
		public IEnumerable<Product> Products { get; set; }
		public PagingInfo PagingInfo { get; set; }
		public string CurrentCategory { get; set; }
	}
}

SportsStore.WebUI/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Extensions;

namespace SportsStore.WebUI.Components
{
	public class CartSummaryViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			var cart = HttpContext.Session.GetObject<Cart>("Cart") ?? new Cart();
			return View(cart);
		}
	}
}

SportsStore.WebUI/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
	[Authorize]
	public class AccountController : Controller
	{
		private readonly IAuthProvider authProvider;

		public AccountController(IAuthProvider _authProvider)
		{
			authProvider = _authProvider;
		}

		[AllowAnonymous]
		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
		[AllowAnonymous]
		public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				if (await authProvider.ValidateCredentialsAsync(model.UserName, model.Password))
				{
					await authProvider.SignInAsync(HttpContext, model.UserName);
					return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
				}

				ModelState.AddModelError("", "Invalid login");
				return View();
			}
			else
			{
				return View();
			}
		}

		public async Task<IActionResult> Logout()
		{
			await authProvider.SignOutAsync(HttpContext);
			return RedirectToAction("Login");
		}
	}
}

SportsStore.WebUI/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
	[Authorize]
	public class AdminController : Controller
	{
		private IProductRepository repository;

		public AdminController(IProductRepository repo)
		{
			repository = repo;
		}

		public ViewResult Index()
		{
			return View(repository.Products);
		}

		public ViewResult Edit(int productId)
		{
			var product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

			return View(product);
		}

		[HttpPost]
		public ActionResult Edit(Product product, IFormFile image)
		{
			if (ModelState.IsValid)
			{
				if (image != null)
				{
					product.ImageMimeType = image.ContentType;

					using (var memoryStream = new MemoryStream())
					{
						image.CopyTo(memoryStream);
						product.ImageData = memoryStream.ToArray();
					}
				}

				repository.Save(product);

				TempData["message"] = string.Format("{0} has been saved", product.Name);
				return RedirectToAction("Index");
			}
			else
			{
				return View(product);
			}
		}

		public ViewResult Create()
		{
			return View("Edit", new Product());
		}

		[HttpPost]
		public ActionResult Delete(int productId)
		{
			Product deletedProduct = repository.Delete(productId);
			if (deletedProduct != null)
			{
				TempData["message"] = string.Format("{0} was deleted", deletedProduct.Name);
			}
			return RedirectToAction("Index");
		}
	}
}

SportsStore.WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Extensions;
using SportsStore.WebUI.Models;
using System.Web.Helpers;

namespace SportsStore.WebUI.Controllers
{
	public class CartController : Controller
	{
		private IProductRepository repository;
		private IOrderProcessor orderProcessor;

		public CartController(IProductRepository repo, IOrderProcessor _orderProcessor)
		{
			repository = repo;
			orderProcessor = _orderProcessor;
		}

		public ViewResult Index(Cart cart, string returnUrl)
		{
			return View(new CartIndexViewModel
			{
				Cart = cart,
				ReturnUrl = returnUrl
			});
		}

		public IActionResult AddToCart(Cart cart, int productId, string returnUrl)
		{
			var product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

			if (product != null)
			{
				cart.AddItem(product, 1);
				HttpContext.Session.SetObject("Cart", cart);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

		public IActionResult RemoveFromCart(Cart cart, int productId, string returnUrl)
		{
			var product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

			if (product != null)
			{
				cart.RemoveLine(product);
				HttpContext.Session.SetObject("Cart", cart);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

		[HttpGet]
		public ViewResult Checkout()
		{
			return View(new ShippingDetails());
		}

		[HttpPost]
		public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
		{
			if (cart.Lines.Count() == 0)
			{
				ModelState.AddModelError("", "Sorry, your cart is empty!");
			}
			if (ModelState.IsValid)
			{
				orderProcessor.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed");
			}
			else
			{
				return View(shippingDetails);
			}
		}
	}
}

SportsStore.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.WebUI.Models;
using System.Diagnostics;

namespace SportsStore.WebUI.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

SportsStore.WebUI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
	public class ProductController : Controller
	{
		private IProductRepository repository;

		public int PageSize = 4;

		public ProductController(IProductRepository productRepository)
		{
			repository = productRepository;
		}

		public ViewResult List(string category, int page = 1)
		{
			ProductsListViewModel model = new ProductsListViewModel
			{
				Products = repository.Products
					.Where(p => category == null || p.Category == category)
					.OrderBy(p => p.ProductID)
					.Skip((page - 1) * PageSize)
					.Take(PageSize),

				PagingInfo = new PagingInfo
				{
					CurrentPage = page,
					ItemsPerPage = PageSize,
					TotalItems = category == null ?
						repository.Products.Count() :
						repository.Products.Where(e => e.Category == category).Count()
				},
				CurrentCategory = category
			};

			ViewBag.SelectedCategory = category;
			return View(model);
		}


		public FileContentResult GetImage(int productId)
		{
			var prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);

			if (prod != null)
			{
				return File(prod.ImageData, prod.ImageMimeType);
			}
			else
			{
				return null;
			}
		}
	}
}

SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product
@{
	ViewBag.Title = "Admin: Edit " + @Model.Name;
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Edit @Model.Name</h1>
@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.EditorForModel()

	<div class="editor-label">Image</div>
	<div class="editor-field">

		@if (Model.ImageData == null)
		{
			@:None
		}
		else
		{
			<img width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
		}

		<div>
			Upload new image:
			<input type="file" name="Image" />
		</div>
	</div>
	<input type="submit" value="Save" />
	@Html.ActionLink("Cancel and return to List", "Index")
}

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>
@{
	ViewBag.Title = "Admin: All Products";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>All Products</h1>
<table class="Grid">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th class="NumericCol">Price</th>
		<th>Actions</th>
	</tr>
	@foreach (var item in Model)
	{
		<tr>
			<td>@item.ProductID</td>
			<td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
			<td class="NumericCol">@item.Price.ToString("c")</td>
			<td>
				@using (Html.BeginForm("Delete", "Admin"))
				{
					@Html.Hidden("ProductID", item.ProductID)
					<input type="submit" value="Delete" />
				}
			</td>
		</tr>
	}
</table>
<p>@Html.ActionLink("Add a new product", "Create")</p>

SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails
@{
	ViewBag.Title = "SportStore: Checkout";
}
<h2>Check out now</h2>
Please enter your details, and we'll ship your goods right away!
@using (Html.BeginForm())
{
	@Html.ValidationSummary()
	<h3>Ship to</h3>
	<div>Name: @Html.EditorFor(x => x.Name)</div>
	<h3>Address</h3>
	<div>Line 1: @Html.EditorFor(x => x.Line1)</div>
	<div>Line 2: @Html.EditorFor(x => x.Line2)</div>
	<div>Line 3: @Html.EditorFor(x => x.Line3)</div>
	<div>City: @Html.EditorFor(x => x.City)</div>
	<div>State: @Html.EditorFor(x => x.State)</div>
	<div>Zip: @Html.EditorFor(x => x.Zip)</div>
	<div>Country: @Html.EditorFor(x => x.Country)</div>
	<h3>Options</h3>
	<label>
		@Html.EditorFor(x => x.GiftWrap)
		Gift wrap these items
	</label>
	<p align="center">
		<input class="actionButtons" type="submit" value="Complete order" />
	</p>
}

SportsStore.WebUI/Views/Cart/Completed.cshtml
@{
	ViewBag.Title = "SportsStore: Order Submitted";
}
<h2>Thanks!</h2>
Thanks for placing your order. We'll ship your goods as soon as possible

SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel
@{
	ViewBag.Title = "Sports Store: Your Cart";
}
<h2>Your cart</h2>
<table width="90%" align="center">
	<thead>
		<tr>
			<th align="center">Quantity</th>
			<th align="left">Item</th>
			<th align="right">Price</th>
			<th align="right">Subtotal</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var line in Model.Cart.Lines)
		{
			<tr>
				<td align="center">@line.Quantity</td>
				<td align="left">@line.Product.Name</td>
				<td align="right">@line.Product.Price.ToString("c")</td>
				<td align="right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
				<td>
					@using (Html.BeginForm("RemoveFromCart", "Cart"))
					{
						@Html.Hidden("ProductId", line.Product.ProductID)
						@Html.HiddenFor(x => x.ReturnUrl)
						<input class="actionButtons" type="submit" value="Remove" />
					}
				</td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<td colspan="3" align="right">Total:</td>
			<td align="right">
				@Model.Cart.ComputeTotalValue().ToString("c")
			</td>
		</tr>
	</tfoot>
</table>
<p align="center" class="actionButtons">
	<a href="@Model.ReturnUrl">Continue shopping</a>
</p>
<p align="center" class="actionButtons">
	<a href="@Model.ReturnUrl">Continue shopping</a>
	@Html.ActionLink("Checkout now", "Checkout")
</p>

SportsStore.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel
@{
	ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
    await Html.RenderPartialAsync("ProductSummary", p);
}

<div class="pager">
	@Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

SportsStore.WebUI/Views/Shared/Components/CartSummary/Default.cshtml
@model SportsStore.Domain.Entities.Cart
<div id="cart">
	<span class="caption">
		<b>Your cart:</b>
		@Model.Lines.Sum(x => x.Quantity) item(s),
		@Model.ComputeTotalValue().ToString("c")
	</span>

	@Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Context.Request.Path + Context.Request.QueryString }, null)
</div>

SportsStore.WebUI/Views/Shared/Components/Nav/Default.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product")

@foreach (var link in Model)
{
	@Html.RouteLink(link, new
	{
		controller = "Product",
		action = "List",
		category = link,
		page = 1
	},
	new
	{
		@class = link == (string)ViewBag.SelectedCategory ? "selected" : null
	})
}

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="item">
	@if (Model.ImageData != null)
	{
		<div style="float: left; margin-right: 20px">
			<img width="75" height="75" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
		</div>
	}
	<h3>@Model.Name</h3>
	@Model.Description
	@using (Html.BeginForm("AddToCart", "Cart"))
	{
		@Html.HiddenFor(x => x.ProductID)
		@Html.Hidden("returnUrl", Context.Request.Path + Context.Request.QueryString)
		<input type="submit" value="+ Add to cart" />
	}
	<h4>@Model.Price.ToString("c")</h4>
</div>

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link href="~/css/Admin.css" type="text/css" rel="stylesheet" />
	<script src="~/js/jquery/jquery.min.js"></script>
	<script src="~/js/jquery-validate/jquery.validate.min.js"></script>
	<script src="/js/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
	<title>@ViewBag.Title</title>
</head>
<body>
	<div>
		@if (TempData["message"] != null)
		{
			<div class="Message">@TempData["message"]</div>
		}
		@RenderBody()
	</div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link href="~/css/site.css" type="text/css" rel="stylesheet" />
</head>
<body>
	<div id="header">
		@await Component.InvokeAsync("CartSummary")
		<div class="title">SPORTS STORE</div>
	</div>
	<div id="categories">
			@await Component.InvokeAsync("Nav", new { category = ViewBag.SelectedCategory })
	</div>
	<div id="content">
		@RenderBody()
	</div>
</body>
</html>